package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"OzonOrderService/graph/model"
	"context"
	"fmt"

	_ "github.com/jackc/pgx/v5/stdlib"
)

// AddToCart is the resolver for the AddToCart field.
func (r *mutationResolver) AddToCart(ctx context.Context, input model.ItemAddInput) (*model.Item, error) {
	return r.CartService.AddProduct(ctx, &input), nil
}

// RemoveFromCart is the resolver for the removeFromCart field.
func (r *mutationResolver) RemoveFromCart(ctx context.Context, input model.ItemRemoveInput) (*model.Cart, error) {
	panic(fmt.Errorf("not implemented: RemoveFromCart - removeFromCart"))
}

// UpdateCartItemsList is the resolver for the UpdateCartItemsList field.
func (r *mutationResolver) UpdateCartItemsList(ctx context.Context, input model.CartUpdateInput) (*model.Cart, error) {
	panic(fmt.Errorf("not implemented: UpdateCartItemsList - UpdateCartItemsList"))
}

// MakeOrder is the resolver for the MakeOrder field.
func (r *mutationResolver) MakeOrder(ctx context.Context, input model.OrderCreateInput) (*model.Order, error) {
	panic(fmt.Errorf("not implemented: MakeOrder - MakeOrder"))
}

// AddProduct is the resolver for the AddProduct field.
func (r *mutationResolver) AddProduct(ctx context.Context, input model.ProductCreateInput) (*model.Product, error) {
	return r.ProductService.Create(ctx, input), nil
}

// AddUser is the resolver for the addUser field.
func (r *mutationResolver) AddUser(ctx context.Context, input model.UserCreateInput) (*model.User, error) {
	return r.UserService.Create(ctx, input), nil
}

// GetProducts is the resolver for the getProducts field.
func (r *queryResolver) GetProducts(ctx context.Context) ([]*model.Product, error) {
	panic(fmt.Errorf("not implemented: GetProducts - getProducts"))
}

// GetOrders is the resolver for the getOrders field.
func (r *queryResolver) GetOrders(ctx context.Context) ([]*model.Order, error) {
	panic(fmt.Errorf("not implemented: GetOrders - getOrders"))
}

// GetOrder is the resolver for the getOrder field.
func (r *queryResolver) GetOrder(ctx context.Context, id int32) (*model.Order, error) {
	panic(fmt.Errorf("not implemented: GetOrder - getOrder"))
}

// GetCart is the resolver for the getCart field.
func (r *queryResolver) GetCart(ctx context.Context, id int32) (*model.Cart, error) {
	panic(fmt.Errorf("not implemented: GetCart - getCart"))
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, id int32) (*model.User, error) {
	panic(fmt.Errorf("not implemented: GetUser - getUser"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
