# GraphQL schema example
#
# https://gqlgen.com/getting-started/

type Cart {
  id: ID!
  userId:ID!
  items: [Item!]
  totalSum: Int
  discount: Int
}

type User {
  id: ID!
  fio: String!
  balance: Int!
}

type Item {
    id: ID!
    productId: ID!
    cartID: ID!
    quantity: Int!
}

type Order{
    id: ID!
    cart: Cart!
    status: String!
    createdAt: String!
}

type Product {
      id: ID!
      name: String!
      price: Int!

}

input ProductCreateInput {
  name: String!
  price: Int!
}
input CartCreateInput {
  userId:ID!
}
input UserCreateInput {
  fio: String!
  balance: Int!

}


input ItemUpdateInput {
    cartId: ID!
    productId: ID!
    quantity: Int!
}

input OrderCreateInput {
  name: String!
  cartId: ID!
}


type Query {
  getProducts: [Product!]!
  getOrders(userID: ID!): [Order!]!
  getOrder(id: ID!): Order!
  getCart(id: ID!): Cart!
  getUser(id: ID!): User!
}

type Mutation {
  addToCart(input: ItemUpdateInput!): Item
  removeFromCart( input:ItemUpdateInput!): Item
  makeOrder(input: OrderCreateInput!): Order
  addProduct(input:ProductCreateInput!): Product
  addUser(input:UserCreateInput!): User
  addCart(input: CartCreateInput!): Cart

}
