// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Cart struct {
	ID       int     `json:"id"`
	UserID   int     `json:"userId"`
	Items    []*Item `json:"items,omitempty"`
	TotalSum int32   `json:"totalSum"`
	Discount int32   `json:"discount"`
}

type CartUpdateInput struct {
	UserID int                `json:"userID"`
	Items  []*ItemUpdateInput `json:"items"`
}

type Item struct {
	ID        int   `json:"id"`
	ProductID int   `json:"productId"`
	Quantity  int32 `json:"quantity"`
}

type ItemAddInput struct {
	UserID    int   `json:"userID"`
	ProductID int   `json:"productId"`
	Quantity  int32 `json:"quantity"`
}

type ItemAddResponse struct {
	ID        int   `json:"id"`
	ProductID int   `json:"productId"`
	Quantity  int32 `json:"quantity"`
}

type ItemRemoveInput struct {
	UserID    int   `json:"userID"`
	ProductID int32 `json:"productId"`
}

type ItemUpdateInput struct {
	ProductID int   `json:"productId"`
	Quantity  int32 `json:"quantity"`
}

type Mutation struct {
}

type Order struct {
	ID        int    `json:"id"`
	Cart      *Cart  `json:"cart"`
	Status    string `json:"status"`
	CreatedAt string `json:"createdAt"`
}

type OrderCreateInput struct {
	Name   string `json:"name"`
	CartID int    `json:"cartId"`
}

type Product struct {
	ID    int    `json:"id"`
	Name  string `json:"name"`
	Price int32  `json:"price"`
}

type ProductCreateInput struct {
	Name  string `json:"name"`
	Price int32  `json:"price"`
}

type Query struct {
}

type User struct {
	ID      int    `json:"id"`
	Fio     string `json:"fio"`
	Balance int32  `json:"balance"`
}

type UserCreateInput struct {
	Fio     string `json:"fio"`
	Balance int32  `json:"balance"`
}
